<h1>Login</h1>

<h3>Don't have an account? Sign up</h3>
<form action="/" method="post">
    <label for="username">Username</label>
    <input  type="text"
            name="username"
            id="username"
    />
    <label for="password">Password</label>
    <input  type="text"
            name="password"
            id="password"
    />
    <input  type="submit"
            value="Login"
            id="login-submit"
    />
</form>