<h1>Login</h1>

<h4>Don't have an account? <a href="/signup">Sign up.</a></h4>
<form action="/logincheck" method="post">
    <label for="username">Username:</label>
    <input  type="text"
            name="username"
            id="username"
    />
    <label for="password">Password:</label>
    <input  type="password"
            name="password"
            id="password"
    />
    <input  type="submit"
            value="Login"
            id="login-submit"
            class="btn btn-default"
    />
</form>