<!-- pvw means preview -->
<div id="pvw">

<h1>Restoration Schedule</h1>

<table id="pvw-table-job">
    <thead>
    <tr>
        <th>Job Number</th>
        <th>Address</th>
        <th>Access</th>
    </tr>
    </thead>
    <tbody>
    <?php
    echo "<tr>
            <td>" . $this->schedInfo['job_id'] . "</td>
            <td>" . $this->schedInfo['address'] . "</td>
            <td>" . $this->schedInfo['access'] . "</td>
          </tr>";
    ?>
    </tbody>

</table>


<table id="pvw-table-row">
    <tr>
        <th class="pvw-row-narrow">Type of Work</th>
        <th class="pvw-row-narrow">Trade</th>
        <th class="pvw-row-narrow">Date In</th>
        <th class="pvw-row-narrow">Date Out</th>
        <th class="pvw-row-wide">Comments</th>
    </tr>

    <?php

    $rowNum = 1;
    foreach($this->rows as $rows) {
        echo "<tr>
                      <td>" . $rows['type_of_work'] . "</td>
                      <td>" . $rows['trade_name'] . "</td>
                      <td>" . $rows['day_in'] . "</td>
                      <td>" . $rows['day_out'] . "</td>
                      <td>" . $rows['comments'] . "</td>
                 </tr>";

        $rowNum++;
    }

    ?>


</table>

</div>






