    <h1>Schedule Maker</h1>

    <form method="post" action="/save">

    <table id="sc-table-job">
        <thead>
        <tr>
            <th>Job Number</th>
            <th>Address</th>
            <th>Access</th>
        </tr>
        </thead>
        <tbody>
        <?php
                 echo "<tr>
                    <td><input type='text' name='sc-job-number' id='sc-job-number' value='" . $this->job['sc-job-number'] . "' /></td>
                    <td><input type='text' name='sc-job-address' id='sc-job-address' value='" . $this->job['sc-job-address'] . "' /></td>
                    <td><textarea name='sc-job-access' id='sc-job-access'>" . $this->job['sc-job-access'] . "</textarea></td>
                  </tr>";
        ?>
        </tbody>

    </table>

        <p>To regenerate dates on the schedule, type a new number in the "Days Needed" column, and press "Enter" on your keyboard.</p>

    <table id="sc-table-row">
        <tr>
            <th>Type of Work</th>
            <th>Trade</th>
            <th>Trade Email</th>
            <th>Date In</th>
            <th>Date Out</th>
            <th>Days Needed</th>
            <th>Comments</th>
        </tr>

        <?php

        $rowNum = 1;
        while(true) {
            if(isset($this->rowOther['sc-row'.$rowNum.'-type'])) {
                echo "<tr>
                      <td><input    type='text' 
                                    name='sc-row" . $rowNum . "-type' 
                                    id='sc-row" . $rowNum . "-type' 
                                    value='" . $this->rowOther['sc-row' . $rowNum . '-type'] . "' 
                          />
                      </td>
                      <td><input    type='text' 
                                    name='sc-row" . $rowNum . "-trade' 
                                    id='sc-row" . $rowNum . "-trade' 
                                    value='" . $this->rowOther['sc-row' . $rowNum . '-trade'] . "' 
                          />
                      </td>
                      <td><input    type='text'
                                    name='sc-row" . $rowNum . "-trade-email'
                                    id='sc-row" . $rowNum . "-trade-email'
                                    value='" . $this->rowOther['sc-row' . $rowNum . '-trade-email'] . "' 
                          />
                      </td>
                      <td><input    type='text' 
                                    name='sc-row" . $rowNum . "-dayIn'
                                    id='sc-row" . $rowNum . "-dayIn'
                                    value='" . $this->rowDayInDayOut['sc-row' . $rowNum . '-dayIn'] . "' 
                          />
                      </td>
                      <td><input    type='text' 
                                    name='sc-row" . $rowNum . "-dayOut' 
                                    id='sc-row" . $rowNum . "-dayOut' 
                                    value='" . $this->rowDayInDayOut['sc-row' . $rowNum . '-dayOut'] . "' 
                          />
                      </td>
                      <td><input    type='text' 
                                    name='sc-row" . $rowNum . "-days' 
                                    id='sc-row" . $rowNum . "-days' 
                                    value='" . $this->rowDaysNeeded['sc-row' . $rowNum . '-days'] . "' 
                          />
                      </td>
                      <td><textarea name='sc-row" . $rowNum . "-comments' 
                                    id='sc-row" . $rowNum . "-comments' 
                          >" . $this->rowOther['sc-row' . $rowNum . '-comments'] . "</textarea>
                      </td>
                    </tr>";

                $rowNum++;
            }
            else {
                break;
            }
        }

        ?>



    </table>

        <input type="submit"
               value="Save"
               class="btn btn-default" />

    </form>

    <script>

        //prevent submit from happening when "enter" key is pressed
        $("input").on("keydown", function(event) {
            if(event.which === 13) {
                event.preventDefault();
            }
        });

        //recalculate dates in schedule draft when "enter" key is pressed
        $("input[id$='-days']").on("keydown", function(event){
            console.log(event.which);
            if(event.which === 13) {
                event.preventDefault();

                var id = this.id;
                console.log(id);
                var rowId = id.replace(/[^\d]/g, '');
                var rowIdStart = rowId;
                var selectedDaysNeeded = this.value;

                console.log(rowId);
                //console.log($("input[type='text']").attr("id"));
                console.log(document.getElementById("sc-row1-dayIn").id);
                console.log(document.getElementById("sc-row1-dayIn").value);



                //initiate daysNeededChange as Javascript object:
                var daysNeededChange = {};

                var selectedElementStartDate = document.getElementById("sc-row" + rowId + "-dayIn").value;

                //get all days needed that are after the current selected element:
                while(true) {
                    if(!document.getElementById("sc-row" + rowId + "-dayIn") || !document.getElementById("sc-row" + rowId + "-dayOut")) {
                        break;
                    }
                    daysNeededChange[document.getElementById("sc-row" + rowId + "-days").id] = document.getElementById("sc-row" + rowId + "-days").value;
                    rowId++;
                }

                console.log(daysNeededChange);



                //convert daysNeededChange array to JSON:
                var daysNeededJson = JSON.stringify(daysNeededChange);

                console.log(daysNeededJson);


                // then call ajax function to change the dates
                updateDates (selectedElementStartDate, daysNeededJson, rowIdStart);


            }
        });

        function updateDates(startDate, daysNeededInJson, selectedRowId) {
            $.ajax({
                url: "/schedule/dates",
                type: "post",
                datatype: "json",
                data: {selectedStartDate: startDate, followingDaysNeeded: daysNeededInJson, rowId: selectedRowId},

                success: function(updatedDates) {

                   $.each(updatedDates, function(index, element) {
                        $("#" + index).val(element);
                   });


                }

            });
        }





        //recalculate dates in schedule draft when "enter" key is pressed, for the actual date
        $("input[id$='-dayIn']").on("keydown", function(event){
            console.log(event.which);
            if(event.which === 13) {
                event.preventDefault();

                var dayInId = this.id;
                var dayOutId = dayInId.replace(/dayIn/g, 'dayOut');

                console.log(dayInId, "day in id");
                console.log(dayOutId, "day out id");

                var dayInValue = this.value;
                var dayOutValue = document.getElementById(dayOutId).value;

                console.log(dayInValue, "Day in value");
                console.log(dayOutValue, "Day out value");








                var rowId = dayInId.replace(/[^\d]/g, '');
                console.log(rowId, "rowId");
                var rowIdStart = rowId;

                console.log(rowId);
                //console.log($("input[type='text']").attr("id"));
                //console.log(document.getElementById("sc-row1-dayIn").id);
                //console.log(document.getElementById("sc-row1-dayIn").value);



                //initiate daysNeededChange as Javascript object:
                var daysNeededChange = {};

                var selectedElementStartDate = document.getElementById("sc-row" + rowId + "-dayIn").value;

                //get all days needed that are after the current selected element:
                while(true) {
                    if(!document.getElementById("sc-row" + rowId + "-dayIn") || !document.getElementById("sc-row" + rowId + "-dayOut")) {
                        break;
                    }
                    daysNeededChange[document.getElementById("sc-row" + rowId + "-days").id] = document.getElementById("sc-row" + rowId + "-days").value;
                    rowId++;
                }

                console.log(daysNeededChange);



                //convert daysNeededChange array to JSON:
                var daysNeededJson = JSON.stringify(daysNeededChange);

                console.log(daysNeededJson);


                // then call ajax function to change the dates
                updateDates (selectedElementStartDate, daysNeededJson, rowIdStart);


            }
        });




    </script>

