    <h1>Schedule Maker</h1>

    <form method="post" action="/save">

    <table id="sc-table-job">
        <thead>
        <tr>
            <th>Job Number</th>
            <th>Address</th>
            <th>Access</th>
        </tr>
        </thead>
        <tbody>
        <?php
                 echo "<tr>
                    <td><input type='text' name='sc-job-number' id='sc-job-number' value='" . $this->job['sc-job-number'] . "' /></td>
                    <td><input type='text' name='sc-job-address' id='sc-job-address' value='" . $this->job['sc-job-address'] . "' /></td>
                    <td><textarea name='sc-job-access' id='sc-job-access'>" . $this->job['sc-job-access'] . "</textarea></td>
                  </tr>";
        ?>
        </tbody>

    </table>



    <table id="sc-table-row">
        <tr>
            <th>Type of Work</th>
            <th>Trade</th>
            <th>Trade Email</th>
            <th>Date In</th>
            <th>Date Out</th>
            <th>Days Needed</th>
            <th>Comments</th>
        </tr>

        <?php

        $rowNum = 1;
        while(true) {
            if(isset($this->rowOther['sc-row'.$rowNum.'-type'])) {
                echo "<tr>
                      <td><input    type='text' 
                                    name='sc-row" . $rowNum . "-type' 
                                    id='sc-row" . $rowNum . "-type' 
                                    value='" . $this->rowOther['sc-row' . $rowNum . '-type'] . "' 
                          />
                      </td>
                      <td><input    type='text' 
                                    name='sc-row" . $rowNum . "-trade' 
                                    id='sc-row" . $rowNum . "-trade' 
                                    value='" . $this->rowOther['sc-row' . $rowNum . '-trade'] . "' 
                          />
                      </td>
                      <td><input    type='text'
                                    name='sc-row" . $rowNum . "-trade-email'
                                    id='sc-row" . $rowNum . "-trade-email'
                                    value='" . $this->rowOther['sc-row' . $rowNum . '-trade-email'] . "' 
                          />
                      </td>
                      <td><input    type='text' 
                                    name='sc-row" . $rowNum . "-dayIn'
                                    id='sc-row" . $rowNum . "-dayIn'
                                    value='" . $this->rowDayInDayOut['sc-row' . $rowNum . '-dayIn'] . "' 
                          />
                      </td>
                      <td><input    type='text' 
                                    name='sc-row" . $rowNum . "-dayOut' 
                                    id='sc-row" . $rowNum . "-dayOut' 
                                    value='" . $this->rowDayInDayOut['sc-row' . $rowNum . '-dayOut'] . "' 
                          />
                      </td>
                      <td><input    type='text' 
                                    name='sc-row" . $rowNum . "-days' 
                                    id='sc-row" . $rowNum . "-days' 
                                    value='" . $this->rowDaysNeeded['sc-row' . $rowNum . '-days'] . "' 
                          />
                      </td>
                      <td><textarea name='sc-row" . $rowNum . "-comments' 
                                    id='sc-row" . $rowNum . "-comments' 
                          >" . $this->rowOther['sc-row' . $rowNum . '-comments'] . "</textarea>
                      </td>
                    </tr>";

                $rowNum++;
            }
            else {
                break;
            }
        }

        ?>



    </table>

        <input type="submit"
               value="Save"
               class="btn btn-default" />

    </form>

    <script>
        //recalculate dates in schedule draft when "enter" key is pressed
        $("input[id$='-days']").on("keydown", function(event){
            console.log(event.which);
            if(event.which === 13) {
                event.preventDefault();

                var id = this.id;
                console.log(id);
                var rowId = id.replace(/[^\d]/g, '');
                var rowIdStart = rowId;
                var selectedDaysNeeded = this.value;

                console.log(rowId);
                //console.log($("input[type='text']").attr("id"));
                console.log(document.getElementById("sc-row1-dayIn").id);
                console.log(document.getElementById("sc-row1-dayIn").value);



                //var daysInChange = [];
                //var daysOutChange = [];

                //initiate daysNeededChange as Javascript object:
                var daysNeededChange = {};

                var selectedElementStartDate = document.getElementById("sc-row" + rowId + "-dayIn").value;

                //get all days needed that are after the current selected element:
                while(true) {
                    if(!document.getElementById("sc-row" + rowId + "-dayIn") || !document.getElementById("sc-row" + rowId + "-dayOut")) {
                        break;
                    }
                    //daysInChange[document.getElementById("sc-row" + rowId + "-dayIn").id] = document.getElementById("sc-row" + rowId + "-dayIn").value;
                    //daysOutChange[document.getElementById("sc-row" + rowId + "-dayOut").id] = document.getElementById("sc-row" + rowId + "-dayOut").value;
                    daysNeededChange[document.getElementById("sc-row" + rowId + "-days").id] = document.getElementById("sc-row" + rowId + "-days").value;
                    rowId++;
                }

                //console.log(daysInChange);
                //console.log(daysOutChange);
                console.log(daysNeededChange);


                //var selectedDayIn = document.getElementById("sc-row" + rowId + "-dayIn").value;
                //var selectedDayOut = document.getElementById("sc-row" + rowId + "-dayOut").value;

                /*console.log(selectedDayIn);
                console.log(selectedDayOut);
                console.log(selectedDaysNeeded);*/

                /*var $value = $("sc-row1-dayIn").value;
                $value = "hi";

                console.log($value);*/


                //convert daysNeededChange array to JSON:
                var daysNeededJson = JSON.stringify(daysNeededChange);

                console.log(daysNeededJson);


                // then call a function to change the dates
                updateDates (selectedElementStartDate, daysNeededJson, rowIdStart);

                /*$.ajax({
                    url: "/schedule/dates",
                    type: "post",
                    datatype: "json",
                    data: {initialDayIn: selectedDayIn, initialDayOut: selectedDayOut, initialDaysNeeded: selectedDaysNeeded},

                    success: function(updatedDates) {
                        /!*$("sc-row" + rowId + "-dayIn").value = updatedDates["rowDayIn"];
                         $("sc-row" + rowId + "-dayOut").value = updatedDates["rowDayOut"];

                         console.log(updatedDates["rowDayIn"]);
                         console.log(updatedDates["rowDayOut"]);*!/



                        $("#sc-row" + rowId + "-dayIn").val(updatedDates.finalDayIn);
                        $("#sc-row" + rowId + "-dayOut").val(updatedDates.finalDayOut);


                    }

                });*/

            }
        });

        function updateDates(startDate, daysNeededInJson, selectedRowId) {
            $.ajax({
                url: "/schedule/dates",
                type: "post",
                datatype: "json",
                data: {selectedStartDate: startDate, followingDaysNeeded: daysNeededInJson, rowId: selectedRowId},

                success: function(updatedDates) {
                    /*$("sc-row" + rowId + "-dayIn").value = updatedDates["rowDayIn"];
                    $("sc-row" + rowId + "-dayOut").value = updatedDates["rowDayOut"];

                    console.log(updatedDates["rowDayIn"]);
                    console.log(updatedDates["rowDayOut"]);*/

                   /* $("#sc-row" + rowId + "-dayIn").val(updatedDates.finalDayIn);
                    $("#sc-row" + rowId + "-dayOut").val(updatedDates.finalDayOut);*/

                   $.each(updatedDates, function(index, element) {
                        $("#" + index).val(element);
                   });

                    /*$("#sc-row" + selectedRowId + "-dayIn").val(updatedDates.(sc-row + selectedRowId + -dayIn));
                    $("#sc-row" + selectedRowId + "-dayOut").val(updatedDates.finalDayOut);*/


                }

            });
        }


    </script>

    <!--<form method="post" action="/">
        <input type="input"
               name="job"
               id="job"
               value='<?php /*echo json_encode($this->job); */?>'
        />
        <input type="input"
               name="rowOther"
               id="rowOther"
               value='<?php /*echo json_encode($this->rowOther); */?>'
        />
        <input type="input"
               name="rowDayInDayOut"
               id="rowDayInDayOut"
               value='<?php /*echo json_encode($this->rowDayInDayOut); */?>'
        />
        <input type="submit" value="Edit" />
    </form>-->

<!--    <form method="post" action="/save">
        <input type="hidden"
               name="job"
               id="job"
               value="<?php /*echo json_encode($this->job); */?>"/>
        <input type="hidden"
               name="rowOther"
               id="rowOther"
               value="<?php /*echo json_encode($this->rowOther); */?>"/>
        <input type="hidden"
               name="rowDayInDayOut"
               id="rowDayInDayOut"
               value="<?php /*echo json_encode($this->rowDayInDayOut); */?>"/>
        <input type="submit" value="Save" />
    </form>-->


    <!--<script>

        $(function () {
            //Read more: http://ssiddique.info/jquery-and-editable-html-table.html#ixzz4noYAlhGX
            //1. Creating Editable cell in HTML table
            $("td").dblclick(function () {
                var OriginalContent = $(this).text();
                $(this).addClass("cellEditing");
                $(this).html("<input type='text' value='" + OriginalContent + "' />");

                $(this).children().first().focus();

                $(this).children().first().keypress(function (e) {
                    if (e.which == 13) {
                        var newContent = $(this).val();
                        $(this).parent().text(newContent);
                        $(this).parent().removeClass("cellEditing");
                    }
                });

                $(this).children().first().blur(function () {
                    $(this).parent().text(OriginalContent);
                    $(this).parent().removeClass("cellEditing");
                });

                $(this).find('input').dblclick(function(e){
                    e.stopPropagation();
                });
            });

            //Code for Ajax
            $(this).children().first().keypress(function (e) {
                if (e.which == 13) {
                    var fullContent = $(this).val();
                    $(this).parent().html(fullContent);
                    $(this).parent().removeClass("cellEditing");
                    //Call the server side file to communicate with database.
                    var URL = '/save';
                    //alert (URL);
                    var xmlhttp;
                    if (window.XMLHttpRequest) {
                        // code for IE7+, Firefox, Chrome, Opera, Safari
                        xmlhttp = new XMLHttpRequest();
                    }
                    else {
                        // code for IE6, IE5
                        xmlhttp = new ActiveXObject("Microsoft.XMLHTTP");
                    }
                    xmlhttp.onreadystatechange = function () {
                        // if successfully done it will return status 200
                        if (xmlhttp.readyState == 4 && xmlhttp.status != 200) {
                            alert('Can not update comment. Contact admin')
                        }

                    };
                    xmlhttp.open("POST", URL, true);
                    xmlhttp.send();
                }
            });

        });
    </script>-->


