<h1>Sign Up</h1>

<h4>Already have an account? <a href="/login">Log in.</a></h4>
<form action="/thanks" method="post">
    <label for="firstname">First Name:</label>
    <input  type="text"
            name="firstname"
            id="firstname"
    />
    <label for="lastname">Last Name:</label>
    <input  type="text"
            name="lastname"
            id="lastname"
    />
    <label for="email">Email:</label>
    <input  type="text"
            name="email"
            id="email"
    />
    <label for="phone">Phone:</label>
    <input  type="text"
            name="phone"
            id="phone"
    />
    <!--should use javascript to automatically generate username, and prevent user from entering their own custom name-->
    <label for="username">Username:</label>
    <input  type="text"
            name="username"
            id="username"
    />
    <label for="password">Password:</label>
    <input  type="password"
            name="password"
            id="password"
    />
    <input  type="submit"
            value="Sign Up"
            id="signup-submit"
            class="btn btn-default"
    />
</form>