<h1>Scheduler Web Application for Trades/Contractors</h1>
<h4>Welcome to the demo page! Head to the <a href="/login">log in</a> page to get started.</h4>
<h4>Project is a <strong>work in progress</strong>, so you may experience bugs or unexpected results. Project is updated
    frequently.</h4>

<hr/>

<h3>Summary of Application:</h3>


<p>My current job involves manually creating work schedules in Microsoft Word. Application will make schedule creation
    easy and more automated. Schedules can be automatically emailed to trades/contractors at a time specified by an
    authenticated user.</p>

<div id="highlights">
    <h3>Current Highlights:</h3>
    <ul>
        <li>Designed front-end and back-end architecture based on Model-View-Control concepts.</li>
        <li> Used dependency injections in factories to create database connections and sessions</li>
        <li> Used Zend Framework's Bcrypt library to encrypt passwords before storing them to the database. Only
            authenticated users can create schedules.
        </li>
        <li> Implemented user authentication and access filtering through creating service classes and event listeners.
            Non-authenticated user will be redirected to the login page if they visit a page they do not have access to.
        </li>
        <li> Integrated option for user to download schedule as PDF file or email to trades/contractors, after schedule
            has been generated.
        </li>
        <li> Developed regular expressions and functions with PHP to generate dates that fall on Monday to Friday
            (excludes weekends). Dates generation is based on a start date that the user provides.
        </li>
        <li> Built function to insert or remove more rows of inputs when user clicks add or delete buttons, and send
            these additional inputs to be stored to a database.
        </li>
    </ul>
</div>


<h3>Other main features for the project that I have not yet implemented:</h3>
<ul>
    <li>Upon emailing a schedule to a trade, there is a confirmation button in the email. If the trade clicks on the
        button, it will open up a browser window and redirect the trade to the Scheduler app, where it will trigger the
        server to send an email to the employee that created the schedule. The email will indicate that the trade has
        viewed and confirmed that they will be attending as per the date listed on the schedule.
    </li>
    <li>Need to implement server side validation for data sent from the client.</li>
    <li>Automatically generate version numbers and date modified each time an existing schedule is edited and saved.</li>
</ul>
